document.getElementById('generate-quote').addEventListener('click', generateQuote);

function generateQuote() {
    const quotes = [
        { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
        { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
        { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
        { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
        { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
        { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
        { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
        { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
        { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
        { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
        { text: "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", author: "Unknown" },
        { text: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
        { text: "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.", author: "Steve Jobs" },
        { text: "People who are crazy enough to think they can change the world, are the ones who do.", author: "Rob Siltanen" },
        { text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
        { text: "Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk. That’s the classic entrepreneur.", author: "Mohnish Pabrai" },
        { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
        { text: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang Von Goethe" },
        { text: "Imagine your life is perfect in every respect; what would it look like?", author: "Brian Tracy" },
        { text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link" },
        { text: "Whether you think you can or think you can’t, you’re right.", author: "Henry Ford" },
        { text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller" },
        { text: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb" },
        { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
        { text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
        { text: "What you lack in talent can be made up with desire, hustle and giving 110% all the time.", author: "Don Zimmer" },
        { text: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
        { text: "Develop an ‘Attitude of Gratitude’. Say thank you to everyone you meet for everything they do for you.", author: "Brian Tracy" },
        { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
        { text: "To see what is right and not do it is a lack of courage.", author: "Confucius" },
        { text: "Reading is to the mind, as exercise is to the body.", author: "Brian Tracy" },
        { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
        { text: "There is nothing impossible to they who will try.", author: "Alexander the Great" },
        { text: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville" },
        { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
        { text: "All progress takes place outside the comfort zone.", author: "Michael John Bobak" },
        { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
        { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
        { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
        { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
        { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
        { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
        { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
        { text: "People who are crazy enough to think they can change the world, are the ones who do.", author: "Rob Siltanen" },
        { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
        { text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },
        { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
        { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
        { text: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
        { text: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
        { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
        { text: "Life is what happens when you’re busy making other plans.", author: "John Lennon" },
        { text: "Get busy living or get busy dying.", author: "Stephen King" },
        { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
        { text: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
        { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
        { text: "Go confidently in the direction of your dreams! Live the life you’ve imagined.", author: "Henry David Thoreau" },
        { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
        { text: "You can, you should, and if you’re brave enough to start, you will.", author: "Stephen King" },
        { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
        { text: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
        { text: "You can do anything, but not everything.", author: "David Allen" },
        { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
        { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
        { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
        { text: "The mind is everything. What you think you become.", author: "Buddha" },
        { text: "An unexamined life is not worth living.", author: "Socrates" },
        { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
        { text: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
        { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
        { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
        { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
        { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
        { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
        { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
        { text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
        { text: "If you really want to do something, you’ll find a way. If you don’t, you’ll find an excuse.", author: "Jim Rohn" },
        { text: "Don’t let what you cannot do interfere with what you can do.", author: "John Wooden" },
        { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
        { text: "Act as if what you do makes a difference. It does.", author: "William James" },
        { text: "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit.", author: "Conrad Hilton" },
        { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
        { text: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville" },
        { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
        { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
        { text: "Do not be embarrassed by your failures, learn from them and start again.", author: "Richard Branson" },
        { text: "What would you do if you weren’t afraid?", author: "Spencer Johnson" },
        { text: "Be content to act, and leave the talking to others.", author: "Baltasar Gracián" },
        { text: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
        { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
        { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
        { text: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
        { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" }
    ];

    const randomIndex = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomIndex];

    document.getElementById('quote-text').textContent = randomQuote.text;
    document.getElementById('quote-author').textContent = `- ${randomQuote.author}`;
}
